services:
  lime_simul_demo:
    image: course_lime-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    network_mode: host
    ipc: host
    devices:
      - /dev/dxg
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=${PULSE_SERVER}
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl:ro
      - /mnt/wslg:/mnt/wslg
      - ./pytwb_ws:/root/pytwb_ws:rw
      - ./bin:/root/bin:rw
      - ./roscommon:/root/roscommon:rw
      - $HOME/.Xauthority:/root/.Xauthority
      - ./practice_ws:/root/practice_ws:rw
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    command: xterm -fa 'Hack' -fs 24 -display ${DISPLAY} -T 'cm main'

